# Generated by Django 4.0.3 on 2022-03-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_userdetail_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='skill',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
