# Generated by Django 4.0.3 on 2022-03-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_userdetail_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='skill',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
