# Generated by Django 4.0.3 on 2022-03-22 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_userdetail_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='skill',
        ),
    ]
