# Generated by Django 4.0.3 on 2022-03-31 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_userdetail_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='slug',
        ),
    ]
