# Generated by Django 4.0.3 on 2022-04-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_userdetail_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
