# Generated by Django 4.0.3 on 2022-04-07 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_photo_userdetail_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='image',
        ),
    ]
