# Generated by Django 4.0.3 on 2022-04-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_userdetail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='phone',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
